# Generated by Django 4.1.7 on 2023-03-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EDUInfoHandler', '0001_initial'),
        ('GuardianInfoHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('index_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('name_with_initials', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('enrolled_date', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('alumni_status', models.BooleanField(default=False)),
                ('special_notes', models.TextField()),
                ('RFID_key', models.CharField(max_length=25)),
                ('Guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuardianInfoHandler.guardianinfo')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDUInfoHandler.classinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('student_index_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudentInfoHandler.studentinfo')),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_nic', models.CharField(max_length=255)),
                ('mother_status', models.CharField(max_length=10)),
                ('mother_special_notes', models.TextField()),
                ('father_name', models.CharField(max_length=255)),
                ('father_nic', models.CharField(max_length=255)),
                ('father_status', models.CharField(max_length=10)),
                ('father_special_notes', models.TextField()),
            ],
        ),
    ]
