# Generated by Django 4.1.7 on 2023-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfoHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='RFID_key',
            field=models.TextField(),
        ),
    ]
