# Generated by Django 4.1.7 on 2023-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StudentInfoHandler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentinfo",
            name="father_dob",
            field=models.CharField(default="1969/02/23", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentinfo",
            name="father_job",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentinfo",
            name="mother_dob",
            field=models.CharField(default="1973/05/21", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentinfo",
            name="mother_job",
            field=models.CharField(default="house wife", max_length=255),
            preserve_default=False,
        ),
    ]
