# Generated by Django 4.1.7 on 2023-04-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0001_initial"),
        ("StudentInfoHandler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="class_info",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="EDUInfoHandler.classinfo",
            ),
            preserve_default=False,
        ),
    ]
