# Generated by Django 4.1.6 on 2023-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfoHandler', '0002_studentinfo_class_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinfo',
            name='father_contact_number',
            field=models.CharField(default=1111111111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='mother_contact_number',
            field=models.CharField(default=1111111111, max_length=255),
            preserve_default=False,
        ),
    ]
