# Generated by Django 4.1.7 on 2023-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "StudentInfoHandler",
            "0002_parentinfo_father_dob_parentinfo_father_job_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="index_number",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
