# Generated by Django 4.1.7 on 2023-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StudentInfoHandler", "0003_alter_studentinfo_index_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="buckets",
            field=models.CharField(default="", max_length=20),
        ),
    ]
