# Generated by Django 4.1.7 on 2023-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('name_with_initials', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=1)),
                ('job', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=2)),
                ('special_notes', models.TextField()),
            ],
        ),
    ]
