# Generated by Django 4.1.7 on 2023-03-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("EDUInfoHandler", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("name_with_initials", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("nic", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("post", models.CharField(max_length=50)),
                ("special_notes", models.JSONField()),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=12)),
                ("enrolled_date", models.DateField(auto_now=True)),
                ("started_date", models.DateField(auto_now=True)),
                (
                    "class_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="EDUInfoHandler.classinfo",
                    ),
                ),
            ],
        ),
    ]
