# Generated by Django 4.1.7 on 2023-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherInfoHandler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherinfo",
            name="enrolled_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="started_date",
            field=models.DateField(),
        ),
    ]
