# Generated by Django 4.1.6 on 2023-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherInfoHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_grade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
