# Generated by Django 4.1.7 on 2023-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherInfoHandler", "0002_alter_teacherinfo_enrolled_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherinfo",
            name="password",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
