# Generated by Django 4.1.6 on 2023-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherInfoHandler', '0002_teacherinfo_teacher_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='position',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='special_notes',
            field=models.TextField(),
        ),
    ]
