# Generated by Django 4.1.7 on 2023-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherInfoHandler", "0003_teacherinfo_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherinfo",
            name="position",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="qr_key",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
