# Generated by Django 4.1.7 on 2023-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherInfoHandler", "0004_teacherinfo_position_teacherinfo_qr_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherinfo",
            name="subjects",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
