# Generated by Django 4.1.7 on 2023-04-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("StudentInfoHandler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=10)),
                ("class_type", models.CharField(max_length=10)),
                ("visibility", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=20)),
                ("acc_type", models.CharField(max_length=25)),
                ("identifier", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("range", models.CharField(max_length=10)),
                ("bucket", models.BooleanField()),
                ("bucket_subjects", models.CharField(max_length=100)),
                ("subject_visibility", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam", models.CharField(max_length=100)),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("marks", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StudentInfoHandler.studentinfo",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EDUInfoHandler.subjectinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("intime", models.CharField(max_length=50)),
                ("outtime", models.CharField(default=None, max_length=50)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StudentInfoHandler.studentinfo",
                    ),
                ),
            ],
        ),
    ]
