# Generated by Django 4.1.7 on 2023-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectinfo",
            name="subject_visibility",
        ),
        migrations.AddField(
            model_name="subjectinfo",
            name="vis",
            field=models.BooleanField(default=True),
        ),
    ]
