# Generated by Django 4.1.7 on 2023-03-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EDUInfoHandler', '0001_initial'),
        ('StudentInfoHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentInfoHandler.studentinfo'),
        ),
        migrations.AddField(
            model_name='examinfo',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDUInfoHandler.subjectinfo'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentInfoHandler.studentinfo'),
        ),
    ]
