# Generated by Django 4.1.6 on 2023-05-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDUInfoHandler', '0002_remove_subjectinfo_subject_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='month',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='year',
        ),
        migrations.AddField(
            model_name='examinfo',
            name='term',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EDUInfoHandler.terms'),
            preserve_default=False,
        ),
    ]
