# Generated by Django 4.1.7 on 2023-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUInfoHandler', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
