# Generated by Django 4.1.7 on 2023-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="loginkeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=20)),
            ],
        ),
    ]
