# Generated by Django 4.1.6 on 2023-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUInfoHandler', '0003_terms_remove_examinfo_month_remove_examinfo_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='term_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
