# Generated by Django 4.1.7 on 2023-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUInfoHandler', '0003_subjectinfo_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='exam',
            field=models.CharField(max_length=100),
        ),
    ]
