# Generated by Django 4.1.7 on 2023-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0003_loginkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginkeys",
            name="type",
            field=models.CharField(default="student", max_length=25),
            preserve_default=False,
        ),
    ]
