# Generated by Django 4.1.6 on 2023-05-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDUInfoHandler', '0004_terms_term_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinfo',
            name='exam',
        ),
    ]
