# Generated by Django 4.1.7 on 2023-04-09 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0004_loginkeys_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginkeys",
            old_name="type",
            new_name="acc_type",
        ),
    ]
