# Generated by Django 4.1.7 on 2023-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUInfoHandler', '0004_alter_examinfo_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectinfo',
            name='visibility',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
