# Generated by Django 4.1.7 on 2023-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0005_rename_type_loginkeys_acc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginkeys",
            name="identifier",
            field=models.IntegerField(default=0),
        ),
    ]
