# Generated by Django 4.1.7 on 2023-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0005_remove_subjectinfo_visibility_classinfo_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectinfo",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
