# Generated by Django 4.1.7 on 2023-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0006_loginkeys_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="intime",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="outtime",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
