# Generated by Django 4.1.7 on 2023-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0007_remove_attendance_time_attendance_intime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectinfo",
            name="bucket",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectinfo",
            name="bucket_subjects",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="subjectinfo",
            name="range",
            field=models.CharField(default="other", max_length=10),
            preserve_default=False,
        ),
    ]
