# Generated by Django 4.1.7 on 2023-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "EDUInfoHandler",
            "0008_subjectinfo_bucket_subjectinfo_bucket_subjects_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="classinfo",
            name="class_type",
            field=models.CharField(default="6-9", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subjectinfo",
            name="bucket_subjects",
            field=models.CharField(max_length=100),
        ),
    ]
