# Generated by Django 4.1.7 on 2023-04-24 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EDUInfoHandler", "0009_classinfo_class_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="loginkeys",
            new_name="LoginKey",
        ),
    ]
